### ISSUE TITLE
Test the proposed API call in a working install and add that to examples

### ISSUE THREAD

**Issue by gahujipo** [andweber/loxberry-plugin-kalliope#3]
- [x] Test the proposed API call from Loxone [mentioned here ](http://www.loxwiki.eu/display/LOXBERRY/Kalliope?focusedCommentId=18219302#comment-18219302) in a working Kalliope installation and 
- [x] add that setting to examples in the readme or plugin webinterface to help users getting the project up and running.

**Comment by andweber** [comment]
done with commit f7eae2e

with dd24174 furthermore a repeat function added, e.g. kalliope speaks out text given.

**Comment by gahujipo** [comment]
That works. Thanks. (because of the [other issue](https://github.com/andweber/loxberry-plugin-kalliope/issues/2) only the first time, but it works)
