### ISSUE TITLE
Webfrontent startet nicht

### ISSUE THREAD

**Issue by haujo** [andweber/loxberry-plugin-kalliope#4]
Hallo,
ich habe auf einer frisch eingerichteten Loxberry Umgebung (Version: 0.2.3) das Plugin installiert. Wenn ich im Webfrontend auf das Plugin klicke, dann erscheint endlos das Sybol zum laden, aber das Webfrontend erscheint nicht. Ich verwende einen Raspberry PI 3 Model B.

**Comment by haujo** [comment]
Habe den Raspberry nochmal auf das Image zurück gesetzt vor der Installation und dann die aktuelle source aus github herntergeladen und installiert. Jetzt kommt es zwar über das Symbol zum laden hinaus und es kommt die Seite /admin/plugins/kalliope_loxscontrol/index.cgi, diese ist aber leer (nur grauer Hintergrund).

**Comment by haujo** [comment]
Nun habe ich den Raspberry neu gestartet und es ist wieder wie beim ersten Post, wo nur das Ladesymbol erscheint. Mit fällt ein, dass ich bei der ersten Installation auch neu gestartet hatte ohne es davor zu probieren. Ist also vermutlich die gleiche Situation. Evtl. hilft das ja bei der Fehlersuche.

**Comment by andweber** [comment]
Webbrowser - Plattform?

Workaround: Statt zu klicken, typischerweise über rechtsklick "Link Adresse" kopieren und in der Adresszeile des Browsers einfügen und direkt aufrufen. Sieht in etwa so aus:

``http://<<LOXBERRIP>>/admin/plugins/kalliope_loxscontrol/index.cgi ``

Falls nicht schon geschehen, bitte die Master oder Dev Version installieren:
https://github.com/andweber/loxberry-plugin-kalliope/archive/master.zip
bzw. https://github.com/andweber/loxberry-plugin-kalliope/archive/dev.zip

**Comment by gahujipo** [comment]
Das ist mir auch immer aufgefallen, dass das bei diesem Plugin passiert. Ein Klick mit dem Mausrad war für mich immer der Workaround.

**Comment by andweber** [comment]
@gahujipo: Bitte auch kurze Info zu Plattform und Browser - ich versuche das zu debuggen.

**Comment by gahujipo** [comment]
Chrome auf allen Plattformen.

**Comment by andweber** [comment]
behoben mit neuer Version auf dev; wont-fix in alter version master
